#lang racket
(require racket/class)

(define point% (class object%
                 (super-new)
                 (init-field x y z)
                 (define x-val x)
                 (define y-val y)
                 (define z-val z)
                 (define/public (get-x)
                   x-val)
                 (define/public (get-y)
                   y-val)
                 (define/public (get-z)
                   z-val)
                 (define/public (set-x nx)
                   (set! x-val nx))
                 (define/public (set-y ny)
                   (set! y-val ny))
                 (define/public (set-z nz)
                   (set! z-val nz))
                 (define/public (distance other)
                   (sqrt (+ (+ (expt (- x-val (send other get-x)) 2) (expt (- y-val (send other get-y)) 2))(expt (- z-val (send other get-z)) 2))))
                 (define/public (distance-range otherPoint rangeVal)
                   (<= (send this distance otherPoint)rangeVal))
                 (define/public (triangle-perimeter p2 p3)
                   (+ (+ (send this distance p2)(send this distance p3))(send p2 distance p3)))
                   ))

(define p1 (make-object point% 9 3 6))
(define p2 (make-object point% -1 2 8))
(define p3 (make-object point% 4 5 3))